#!/bin/sh
#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-SensorX" id="HB-UNI-SensorX">
DEVICE="HB-SH-GH"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Gewächshaussensorarray"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-sh-gh.png
DEVICE_THUMB=hb-sh-gh_thumb.png
# Name der Gerätebeschreibungs-Datei .xml
FIRMWARE_FILES=/firmware/rftypes/hb-sh-gh*


#------------------------------------------------------------------------------
# Undo DEVDB.tcl changes
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile


#------------------------------------------------------------------------------
# Undo webui.js changes
webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile
webuiSearch="HBSHGH_TRANSMIT_INTERVAL"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="MOISTURE-1"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="MOISTURE-2"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="MOISTURE-3"
sed -i "/\($webuiSearch\)/d" $webuiFile
webuiSearch="MOISTURE-4"
sed -i "/\($webuiSearch\)/d" $webuiFile

#------------------------------------------------------------------------------
### Undo stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"
stringtable_deSearch="HBSHGH_TRANSMIT_INTERVAL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="MOISTURE-1"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="MOISTURE-2"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="MOISTURE-3"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile
stringtable_deSearch="MOISTURE-4"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile


#------------------------------------------------------------------------------
### Undo translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="stringTableHbShGhAltitude"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableMoisture-1"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableMoisture-2"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableMoisture-3"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile
translate_deSearch="stringTableMoisture-4"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile


#------------------------------------------------------------------------------
### Undo english translate.lang.stringtable.js ###
translate_enFile="/www/webui/js/lang/en/translate.lang.stringtable.js"
translate_enSearch="stringTableHbShGhAltitude"
sed -i "/\(${translate_enSearch}\)/d" $
translate_enSearch="stringTableMoisture-1"
sed -i "/\(${translate_enSearch}\)/d" $
translate_enSearch="stringTableMoisture-2"
sed -i "/\(${translate_enSearch}\)/d" $
translate_enSearch="stringTableMoisture-3"
sed -i "/\(${translate_enSearch}\)/d" $
translate_enSearch="stringTableMoisture-4"
sed -i "/\(${translate_enSearch}\)/d" $

#------------------------------------------------------------------------------
# remove device_xml links
rm -f $FIRMWARE_FILES


#------------------------------------------------------------------------------
# remove image files
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
