#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-SensorX" id="HB-UNI-SensorX">
DEVICE="HB-SH-GH"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Gewächshaussensorarray"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-sh-gh.png
DEVICE_THUMB=hb-sh-gh_thumb.png
# Name der Gerätebeschreibungs-Datei .xml
FIRMWARE_FILES=/firmware/rftypes/hb-sh-gh*

### alte Firmware-Dateien entfernen, die neuen werden dann vom rc-script kopiert
rm -f $FIRMWARE_FILES

#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi

#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearchBegin="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="HBSHGH_TRANSMIT_INTERVAL"
webuiInsertValue="stringTableHbShGhTransmitInterval"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi


#------------------------------------------------------------------------------
### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="HBSHGH_TRANSMIT_INTERVAL\t\${stringTableHbShGhTransmitInterval}"
if [ -z "`cat $stringtable_deFile | grep \"HBSHGH_TRANSMIT_INTERVAL"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="MOISTURE-1\t\${stringTableMoisture-1}"
if [ -z "`cat $stringtable_deFile | grep \"MOISTURE-1"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="MOISTURE-2\t\${stringTableMoisture-2}"
if [ -z "`cat $stringtable_deFile | grep \"MOISTURE-2"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="MOISTURE-3\t\${stringTableMoisture-3}"
if [ -z "`cat $stringtable_deFile | grep \"MOISTURE-3"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi

stringtable_deInsert="MOISTURE-4\t\${stringTableMoisture-4}"
if [ -z "`cat $stringtable_deFile | grep \"MOISTURE-4"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


#------------------------------------------------------------------------------
### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbShGhTransmitInterval\" : \"Sendeintervall\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbShGhTransmitInterval\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableMoisture-1\" : \"Bodenfeuchtigkeit 1\","
if [ -z "`cat $translate_deFile | grep \"stringTableMoisture-1\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableMoisture-2\" : \"Bodenfeuchtigkeit 2\","
if [ -z "`cat $translate_deFile | grep \"stringTableMoisture-2\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableMoisture-3\" : \"Bodenfeuchtigkeit 3\","
if [ -z "`cat $translate_deFile | grep \"stringTableMoisture-3\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

translate_deInsert="\n    \"stringTableMoisture-4\" : \"Bodenfeuchtigkeit 4\","
if [ -z "`cat $translate_deFile | grep \"stringTableMoisture-4\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi

#------------------------------------------------------------------------------
### Edit english translate.lang.stringtable.js ###
translate_enFile="/www/webui/js/lang/en/translate.lang.stringtable.js"
translate_enSearch="\"dummy\" : \"\","

translate_enInsert="\n    \"stringTableHbShGhTransmitInterval\" : \"Transmit Interval\","
if [ -z "`cat $translate_enFile | grep \"stringTableHbShGhTransmitInterval\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableMoisture-1\" : \"Soil Moisture 1\","
if [ -z "`cat $translate_enFile | grep \"stringTableMoisture-1\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableMoisture-2\" : \"Soil Moisture 2\","
if [ -z "`cat $translate_enFile | grep \"stringTableMoisture-2\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableMoisture-3\" : \"Soil Moisture 3\","
if [ -z "`cat $translate_enFile | grep \"stringTableMoisture-3\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi

translate_enInsert="\n    \"stringTableMoisture-4\" : \"Soil Moisture 4\","
if [ -z "`cat $translate_enFile | grep \"stringTableMoisture-4\"`" ]; then
	sed -i "s/\($translate_enSearch\)/\1$translate_enInsert/g" $translate_enFile
fi