name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HB-SH-Devices-AddOn
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4  
    - name: Run build script
      run: ./build.sh
