name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HB-SH-Devices-AddOn
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
    - name: Run build script
      run: ./build.sh
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HB-SH-Devices-AddOn
    steps:
      - name: Push TGZ to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "HB-SH-Devices-AddOn.tgz"
          git push